{{- range $key, $value := .Values.resources -}}
{{- $resource := lookup "core.keapio.com/v1alpha1" "ProvisionedService" $.Release.Namespace $value -}}
{{- if or (not $resource) (not $resource.status.binding.name) -}}
  {{- fail (printf "Error: ProvisionedService '%s' or binding not found in namespace '%s'." $value $.Release.Namespace) -}}
{{- end -}}
{{- end -}}
{{- $name := .Release.Name | lower -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  labels:
    app: {{ $name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      containers:
      - name: {{ $name }}
        image: {{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.port }}
        env:
          {{- range $key, $value := .Values.env }}
          {{- if $value }}
           - name: {{ $key }}
             value: {{ $value | quote }}
          {{- end }}
          {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
spec:
  type: LoadBalancer
  selector:
    app: {{ $name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.port }}
{{- range $key, $value := .Values.resources }}
---
apiVersion: servicebinding.io/v1
kind: ServiceBinding
metadata:
  name: {{ $name }}-{{ $key }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
spec:
  service:
    apiVersion: core.keapio.com/v1alpha1
    kind: ProvisionedService
    name: {{ $value }}
  workload:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $name }}
{{- end }}
