# permissions for end users to edit webapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: webapp-operator
    app.kubernetes.io/managed-by: kustomize
  name: webapp-editor-role
rules:
- apiGroups:
  - core.keapio.com
  resources:
  - webapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.keapio.com
  resources:
  - webapps/status
  verbs:
  - get
