---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: webapp
        image: {{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.port }}  # The port the container listens to
        env:  # Optional: Add environment variables
        - name: ENV_VAR_NAME
          value: "value"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  type: ClusterIP  # Use ClusterIP if you don't need an external load balancer
  selector:
    app: {{ .Values.name }}
  ports:
    - protocol: TCP
      port: 80  # Port the service will expose
      targetPort: {{ .Values.port }}  # Port the container listens on
