# permissions for end users to view servers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: mysql-server-operator
    app.kubernetes.io/managed-by: kustomize
  name: server-viewer-role
rules:
- apiGroups:
  - mysql.keapio.com
  resources:
  - servers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mysql.keapio.com
  resources:
  - servers/status
  verbs:
  - get
