apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: webapp-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Keapio WebApp Operator
  displayName: Keapio WebApp
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - webapp
  - platform
  - keapio
  links:
  - name: Webapp Operator
    url: https://webapp-operator.domain
  maturity: alpha
  provider:
    name: Keapio
    url: https://keapio.com
  version: 0.0.0
