# permissions for end users to edit databases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: mysql-database-operator
    app.kubernetes.io/managed-by: kustomize
  name: database-editor-role
rules:
- apiGroups:
  - mysql.keapio.com
  resources:
  - databases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mysql.keapio.com
  resources:
  - databases/status
  verbs:
  - get
