apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
##
## Base operator rules
##
# We need to get namespaces so the operator can read namespaces to ensure they exist
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
# We need to manage Helm release secrets
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - "*"
# We need to create events on CRs about things happening during reconciliation
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create

##
## Rules for mysql.keapio.com/v1alpha1, Kind: Database
##
- apiGroups:
  - mysql.keapio.com
  resources:
  - databases
  - databases/status
  - databases/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- verbs:
  - "*"
  apiGroups:
  - "servicebinding.io"
  resources:
  - "servicebindings"
- verbs:
  - "*"
  apiGroups:
  - "batch"
  resources:
  - "jobs"
#+kubebuilder:scaffold:rules
