{{- $name := .Release.Name | lower -}}
{{- $host := $name -}}
{{- $port := 3306 -}}
{{- $username := "root" -}}
{{- $password := randAlphaNum 25 -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
type: servicebinding.io/mysql
stringData:
  type: mysql
  provider: mariadb
  host: {{ $host }}
  port: {{ $port | quote }}
  username: {{ $username }}
  password: root
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
spec:
  ports:
  - name: mysql
    port: {{ $port }}
    targetPort: mysql
    protocol: TCP
  selector:
    app: {{ $name }}
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  labels:
    app: {{ $name }}
spec:
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      containers:
      - image: mariadb:10.11
        name: mysql
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ $name }}
              key: password
        ports:
        - containerPort: {{ $port }}
          name: mysql
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $name }}-0
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "0"
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
      - name: {{ $name }}-0
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          echo "Waiting for deployment {{ $name }} to be ready..."
          while true; do
            # Check if the deployment is ready
            replicas=$(kubectl get deployment {{ $name }} -n {{ .Release.Namespace }} -o jsonpath='{.status.readyReplicas}')

            # If the number of replicas is empty, set it to 0
            if [ -z "$replicas" ]; then
              replicas=0
            fi

            if [ "$replicas" -eq "1" ]; then
              echo "Deployment {{ $name }} is ready."
              break
            else
              echo "Deployment {{ $name }} is not ready. Waiting..."
              sleep 5
            fi
          done
      restartPolicy: Never
---
apiVersion: core.keapio.com/v1alpha1
kind: ProvisionedService
metadata:
  name: {{ $name }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "1"
spec:
  name: {{ $name }}       
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $name }}-1
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "2"
spec:
  template:
    spec:
      containers:
        - name: {{ $name }}-1
          image: bitnami/kubectl:latest
          command: 
            - /bin/sh
            - -c
            - |
              kubectl patch provisionedservices.core.keapio.com {{ $name }} \
              --type='merge' \
              --subresource=status \
              -p '{"status": {"binding": {"name": "{{ $name }}"}}}'
      restartPolicy: Never
  backoffLimit: 3
