{{- $name := .Release.Name | lower -}}
{{- $host := $name -}}
{{- $port := 3306 -}}
{{- $username := "root" -}}
{{- $password := randAlphaNum 25 -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
type: servicebinding.io/mysql
stringData:
  type: mysql
  provider: mariadb
  host: {{ $host }}
  port: {{ $port | quote }}
  username: {{ $username }}
  password: {{ $password }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
spec:
  ports:
  - port: {{ $port }}
    targetPort: mysql
    protocol: TCP
  selector:
    app: {{ $name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  labels:
    app: {{ $name }}
spec:
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      containers:
      - image: mariadb:10.5
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ $name }}
              key: password
        ports:
        - containerPort: {{ $port }}
          name: mysql
        livenessProbe:
          tcpSocket:
            port: mysql
        readinessProbe:
          tcpSocket:
            port: mysql
        startupProbe:
          tcpSocket:
            port: mysql
---
apiVersion: core.keapio.com/v1alpha1
kind: ProvisionedService
metadata:
  name: {{ $name }}
spec:
  name: {{ $name }}       
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $name }}
  annotations:
    "helm.sh/hook": post-install
spec:
  template:
    spec:
      containers:
        - name: {{ $name }}
          image: bitnami/kubectl:latest
          command: 
            - /bin/sh
            - -c
            - |
              kubectl patch provisionedservices.core.keapio.com {{ $name }} \
              --type='merge' \
              --subresource=status \
              -p '{"status": {"binding": {"name": "{{ $name }}"}}}'
      restartPolicy: Never
  backoffLimit: 3
