# permissions for end users to view domains.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: core-domain-operator
    app.kubernetes.io/managed-by: kustomize
  name: domain-viewer-role
rules:
- apiGroups:
  - core.keapio.com
  resources:
  - domains
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.keapio.com
  resources:
  - domains/status
  verbs:
  - get
