# permissions for end users to edit bindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: core-binding-operator
    app.kubernetes.io/managed-by: kustomize
  name: binding-editor-role
rules:
- apiGroups:
  - core.keapio.com
  resources:
  - bindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.keapio.com
  resources:
  - bindings/status
  verbs:
  - get
